package io.labs.dotanuki.magicmodules.tests

import org.assertj.core.api.Assertions.assertThat
import org.gradle.testkit.runner.GradleRunner
import org.junit.Ignore
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File

class MagicModulesPluginTests {

    @get:Rule val tempFolder = TemporaryFolder()

    @Test fun `should fail when target project missing buildSrc`() {

        val targetProjectDir = prepareFixture("missing_build_src")

        val build = GradleRunner.create()
            .withProjectDir(targetProjectDir)
            .withPluginClasspath()
            .withArguments("clean", "run", "--info")
            .buildAndFail()

        assertThat(build.output).run {
            contains("has no buildSrc build folder defined")
            contains("BUILD FAILED")
        }
    }

    @Test fun `should include multiple modules with custom configuration`() {

        val targetProjectDir = prepareFixture("multiple_modules_custom_config")

        val build = GradleRunner.create()
            .withProjectDir(targetProjectDir)
            .withPluginClasspath()
            .withArguments("clean", ":app:assembleDebug", "--info")
            .build()

        assertThat(build.output).run {
            contains("Included on settings.gradle -> :home")
            contains("Included on settings.gradle -> :login")
            contains("Included on settings.gradle -> :core")
            contains("Included on settings.gradle -> :utils")
            doesNotContain("Included on settings.gradle -> :app")
            contains("BUILD SUCCESS")
        }
    }

    // FIXME: Tests below are ignored because groovy scripts doesn't support inner classes
    /* There is two ways to solve it:
    * 1 - Migrate build.gradle files to kts;
    * 2 - Generated files with modules (JavaModules.kt, etc...) should be inside a package.
    * There is an issue about that: https://github.com/gradle/gradle/issues/9251
    * */

    @Ignore @Test fun `should include multiple nested modules`() {

        val targetProjectDir = prepareFixture("multiple_nested_modules")

        val build = GradleRunner.create()
            .withProjectDir(targetProjectDir)
            .withPluginClasspath()
            .withArguments("clean", ":app:assembleDebug", "--info")
            .build()

        assertThat(build.output).run {
            contains("Included on settings.gradle -> :features:home")
            contains("Included on settings.gradle -> :features:login")
            contains("Included on settings.gradle -> :common:core")
            contains("Included on settings.gradle -> :common:utils")
            contains("Included on settings.gradle -> :app")
            contains("BUILD SUCCESS")
        }

        val mappedLibraries = """
                // Generated by MagicModules plugin. Mind your Linters!
                import kotlin.String
                import kotlin.collections.List
                
                object JavaModules {
                    object Common {
                        const val UTILS: String = ":common:utils"
                
                        val allAvailable: List<String> = 
                                listOf(
                                    UTILS
                                )
                    }
                }
                
            """.trimIndent()

        val generatedCode = targetProjectDir.resolve("buildSrc/src/main/kotlin/JavaModules.kt").readText()

        assertThat(mappedLibraries).isEqualTo(generatedCode)
    }

    @Ignore @Test fun `should include multiple modules and skip some others`() {

        val targetProjectDir = prepareFixture("multiple_nested_modules_with_skip_some")

        val build = GradleRunner.create()
            .withProjectDir(targetProjectDir)
            .withPluginClasspath()
            .withArguments("clean", ":app:assembleDebug", "--info")
            .build()

        assertThat(build.output).run {
            contains("Included on settings.gradle -> :features:home")
            contains("Included on settings.gradle -> :features:login")
            contains("Included on settings.gradle -> :common:core")
            contains("Included on settings.gradle -> :common:utils")
            contains("Included on settings.gradle -> :app")
            contains("Skipping include on settings.gradle -> :features:home")
            contains("Skipping include on settings.gradle -> :features:login")
            contains("BUILD SUCCESS")
        }
    }

    private fun prepareFixture(name: String): File = tempFolder.newFolder().apply {
        File("$TEST_FIXTURES/$name").copyRecursively(this)
    }

    companion object {
        private const val TEST_FIXTURES = "src/test/fixtures/integration"
    }
}